export const data = [
    {
      "bookId": "2767052-the-hunger-games",
      "title": "The Hunger Games",
      "series": "The Hunger Games #1",
      "author": "Suzanne Collins",
      "rating": "4.33",
      "description": "WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.",
      "language": "English",
      "isbn": "9780439023481",
      "genres": "Художественная литература",
      "characters": "['Katniss Everdeen', 'Peeta Mellark', 'Cato (Hunger Games)', 'Primrose Everdeen', 'Gale Hawthorne', 'Effie Trinket', 'Haymitch Abernathy', 'Cinna', 'President Coriolanus Snow', 'Rue', 'Flavius', 'Lavinia (Hunger Games)', 'Marvel', 'Glimmer', 'Clove', 'Foxface', 'Thresh', 'Greasy Sae', 'Madge Undersee', 'Caesar Flickerman', 'Claudius Templesmith', 'Octavia (Hunger Games)', 'Portia (hunger Games)']",
      "bookFormat": "Hardcover",
      "edition": "First Edition",
      "pages": "374",
      "publisher": "Scholastic Press",
      "publishDate": "09/14/08",
      "firstPublishDate": "",
      "awards": "['Locus Award Nominee for Best Young Adult Book (2009)', 'Georgia Peach Book Award (2009)', 'Buxtehuder Bulle (2009)', 'Golden Duck Award for Young Adult (Hal Clement Award) (2009)', Grand Prix de l'Imaginaire Nominee for Roman jeunesse étranger (2010), 'Books I Loved Best Yearly (BILBY) Awards for Older Readers (2012)', West Australian Young Readers' Book Award (WAYRBA) for Older Readers (2010), Red House Children's Book Award for Older Readers & Overall (2010), 'South Carolina Book Award for Junior and Young Adult Book (2011)', 'Charlotte Award (2010)', 'Colorado Blue Spruce Young Adult Book Award (2010)', 'Teen Buckeye Book Award (2009)', Pennsylvania Young Readers' Choice Award for Young Adults (2010), 'Rhode Island Teen Book Award (2010)', Dorothy Canfield Fisher Children's Book Award (2010), 'Evergreen Teen Book Award (2011)', 'Soaring Eagle Book Award (2009)', 'Milwaukee County Teen Book Award Nominee (2010)', 'Sakura Medal for Middle School Book (2010)', 'Michigan Library Association Thumbs Up! Award (2009)', 'Florida Teens Read (2009)', 'Deutscher Jugendliteraturpreis for Preis der Jugendjury (2010)', 'Iowa High School Book Award (2011)', 'New Mexico Land of Enchantment Award for Young Adult (2011)', 'Eliot Rosewater Indiana High School Book Award (2010)', 'The Inky Awards for Silver Inky (2009)', 'California Young Readers Medal for Young Adult (2011)', 'Lincoln Award (2011)', 'Kinderboekwinkelprijs (2010)', 'Missouri Truman Readers Award (2011)', 'CYBILS Award for Young Adult Fantasy & Science Fiction (2008)', 'Literaturpreis der Jury der jungen Leser for Jugendbuch (2010)', 'The Inky Awards Shortlist for Silver Inky (2009)', 'Prix Et-lisez-moi (2011)', 'Missouri Gateway Readers Award (2011)', 'Oklahoma Sequoyah Award for High School and Intermediate (2011)', 'Premio El Templo de las Mil Puertas for Mejor novela extranjera perteneciente a saga (2009)', Rebecca Caudill Young Readers' Book Award (2011), 'LovelyBooks Leserpreis for Fantasy (2009)', 'LovelyBooks Leserpreis for Bestes Cover/Umschlag (2009)', 'Premi Protagonista Jove for Categoria 13-14 anys (2010)']",
      "numRatings": "6376780",
      "ratingsByStars": "['3444695', '1921313', '745221', '171994', '93557']",
      "likedPercent": "96",
      "setting": "['District 12, Panem', 'Capitol, Panem', 'Panem (United States)']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975l/2767052.jpg",
      "bbeScore": "2993816",
      "bbeVotes": "30516",
      "price": "5.09",
      "reviews": [
        {
          "id": "0",
          "name": "John",
          "content": "The best book ever",
          "rating": "5.00"
        },
        { "id": "1", "name": "Ann", "content": "Terrible", "rating": "3.10" }
      ]
    },
    {
      "bookId": "2.Harry_Potter_and_the_Order_of_the_Phoenix",
      "title": "Harry Potter and the Order of the Phoenix",
      "series": "Harry Potter #5",
      "author": "J.K. Rowling, Mary GrandPré (Illustrator)",
      "rating": "4.50",
      "description": "There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey",
      "language": " a big surprise on the Gryffindor Quidditch team",
      "isbn": " and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all.",
      "genres": "Книги для детей",
      "characters": "9780439358071",
      "bookFormat": "['Fantasy', 'Young Adult', 'Fiction', 'Magic', 'Childrens', 'Adventure', 'Audiobook', 'Middle Grade', 'Classics', 'Science Fiction Fantasy']",
      "edition": "['Sirius Black', 'Draco Malfoy', 'Ron Weasley', 'Petunia Dursley', 'Vernon Dursley', 'Dudley Dursley', 'Severus Snape', 'Rubeus Hagrid', 'Lord Voldemort', 'Minerva McGonagall', 'Neville Longbottom', 'Fred Weasley', 'George Weasley', 'Percy Weasley', 'Ginny Weasley', 'Colin Creevey', 'Filius Flitwick', 'Gilderoy Lockhart', 'Lucius Malfoy', 'Pomona Sprout', 'Arthur Weasley', 'Molly Weasley', 'Cho Chang', 'Cornelius Fudge', 'Remus Lupin', 'Sybil Trelawney', 'Stan Shunpike', 'Bellatrix Lestrange', 'Alastor Moody', 'Rita Skeeter', 'Luna Lovegood', 'Nymphadora Tonks', 'Dolores Umbridge', 'Dobby', 'Kingsley Shacklebolt', 'Padma Patil', 'Parvati Patil', 'Kreacher', 'Dean Thomas', 'Seamus Finnigan', 'Albus Dumbledore', 'Harry Potter', 'Hermione Granger', 'Lavender Brown']",
      "pages": "Paperback",
      "publisher": "US Edition",
      "publishDate": "870",
      "firstPublishDate": "Scholastic Inc.",
      "awards": "09/28/04",
      "numRatings": "06/21/03",
      "ratingsByStars": "['Bram Stoker Award for Works for Young Readers (2003)', 'Anthony Award for Young Adult (2004)', Mythopoeic Fantasy Award for Children's Literature (2008), 'Audie Award for Audiobook of the Year (2004)', 'Books I Loved Best Yearly (BILBY) Awards for Older Readers (2004)', 'Colorado Blue Spruce Young Adult Book Award (2006)', 'Golden Archer Award for Middle/Junior High (2005)', 'Deutscher Jugendliteraturpreis Nominee for Preis der Jugendjury (2004)', 'Carnegie Medal Nominee (2003)']",
      "likedPercent": "2507623",
      "setting": "['1593642', '637516', '222366', '39573', '14526']",
      "coverImg": "98",
      "bbeScore": "['Hogwarts School of Witchcraft and Wizardry (United Kingdom)', 'London, England']",
      "bbeVotes": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
      "price": "2632233",
      "reviews": [
        {
          "id": "0",
          "name": "Sam",
          "content": "Perfect gift for a kid",
          "rating": "4.60"
        },
        { "id": "1", "name": "Ann", "content": "Boring", "rating": "2.10" }
      ]
    },
    {
      "bookId": "2657.To_Kill_a_Mockingbird",
      "title": "To Kill a Mockingbird",
      "series": "To Kill a Mockingbird",
      "author": "Harper Lee",
      "rating": "4.28",
      "description": "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.",
      "language": "English",
      "isbn": "9999999999999",
      "genres": "Художественная литература",
      "characters": "['Scout Finch', 'Atticus Finch', 'Jem Finch', 'Arthur Radley', 'Mayella Ewell', 'Aunt Alexandra', 'Bob Ewell', 'Calpurnia (housekeeper)', 'Tom Robinson', 'Miss Maudie Atkinson', 'Judge John Taylor', 'Dill Harris', 'Heck Tate', 'Stephanie Crawford']",
      "bookFormat": "Paperback",
      "edition": "",
      "pages": "324",
      "publisher": "Harper Perennial Modern Classics",
      "publishDate": "05/23/06",
      "firstPublishDate": "07/11/60",
      "awards": "['Pulitzer Prize for Fiction (1961)', 'Audie Award for Classic (2007)', 'National Book Award Finalist for Fiction (1961)', 'Alabama Author Award for Fiction (1961)']",
      "numRatings": "4501075",
      "ratingsByStars": "['2363896', '1333153', '573280', '149952', '80794']",
      "likedPercent": "95",
      "setting": "['Maycomb, Alabama (United States)']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg",
      "bbeScore": "2269402",
      "bbeVotes": "23328",
      "price": ""
    },
    {
      "bookId": "1885.Pride_and_Prejudice",
      "title": "Pride and Prejudice",
      "series": "",
      "author": "Jane Austen, Anna Quindlen (Introduction)",
      "rating": "4.26",
      "description": "Alternate cover edition of ISBN 9780679783268Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work her own darling child and its vivacious heroine, Elizabeth Bennet, as delightful a creature as ever appeared in print. The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.",
      "language": "English",
      "isbn": "9999999999999",
      "genres": "Художественная литература",
      "characters": "['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', 'Elizabeth Bennet', 'Mary Bennet', 'Kitty Bennet', 'Lydia Bennet', 'Louisa Hurst', 'Caroline Bingley', 'Fitzwilliam Darcy', 'Georgiana Darcy', 'Lady Catherine de Bourgh', 'Anne de Bourgh', 'Colonel Fitzwilliam', 'Mr. Gardiner', 'Mrs. Gardiner', 'Sir William Lucas', 'Lady Lucas', 'Charlotte Lucas', 'Maria Lucas', 'Mr. Darcy', 'Charles Bingley', 'George Wickham', 'Mr. William Collins']",
      "bookFormat": "Paperback",
      "edition": "Modern Library Classics, USA / CAN",
      "pages": "279",
      "publisher": "Modern Library",
      "publishDate": "10/10/00",
      "firstPublishDate": "01/28/13",
      "awards": "[]",
      "numRatings": "2998241",
      "ratingsByStars": "['1617567', '816659', '373311', '113934', '76770']",
      "likedPercent": "94",
      "setting": "['United Kingdom', 'Derbyshire, England (United Kingdom)', 'England', 'Hertfordshire, England (United Kingdom)']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320399351l/1885.jpg",
      "bbeScore": "1983116",
      "bbeVotes": "20452",
      "price": ""
    },
    {
      "bookId": "41865.Twilight",
      "title": "Twilight",
      "series": "The Twilight Saga #1",
      "author": "Stephenie Meyer",
      "rating": "3.60",
      "description": "About three things I was absolutely positive. First, Edward was a vampire. Second, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood. And third, I was unconditionally and irrevocably in love with him.Deeply seductive and extraordinarily suspenseful, Twilight is a love story with bite.",
      "language": "English",
      "isbn": "9780316015844",
      "genres": "Художественная литература",
      "characters": "['Edward Cullen', 'Jacob Black', 'Laurent', 'Renee', 'Bella Swan', 'Billy Black', 'Esme Cullen', 'Alice Cullen', 'Jasper Hale', 'Carlisle Cullen', 'Emmett Cullen', 'Rosalie Hale', 'Charlie Swan', 'Mike Newton', 'Jessica Stanley', 'Angela Weber', 'Tyler Crowley']",
      "bookFormat": "Paperback",
      "edition": "",
      "pages": "501",
      "publisher": "Little, Brown and Company",
      "publishDate": "09/06/06",
      "firstPublishDate": "10/05/05",
      "awards": "['Georgia Peach Book Award (2007)', 'Buxtehuder Bulle (2006)', 'Kentucky Bluegrass Award for 9-12 (2007)', 'Prijs van de Kinder- en Jeugdjury Vlaanderen (2008)', 'Books I Loved Best Yearly (BILBY) Awards for Older Readers (2009)', West Australian Young Readers' Book Award (WAYRBA) for Older Readers (2008), 'Garden State Book Award for Fiction (Grades 9-12) (2008)', 'South Carolina Book Award for Young Adult Book Award (2008)', 'Grand Canyon Reader Award for Teen Book (2008)', 'Maryland Black-Eyed Susan Book Award for High School (2008)', 'Golden Sower Award for Young Adult (2009)', Nevada Young Readers' Award for Young Adult Category  (2007), The Flume: New Hampshire Teen Reader's Choice Award (2007), Pennsylvania Young Readers' Choice Award for Young Adult (2009), 'Rhode Island Teen Book Award (2007)', 'Evergreen Teen Book Award (2008)', 'Michigan Library Association Thumbs Up! Award Nominee (2006)', 'Teen Read Award Nominee for Best All-Time-Fave (2010)', 'Deutscher Jugendliteraturpreis Nominee for Preis der Jugendjury (2007)', 'Iowa High School Book Award (2008)', 'Eliot Rosewater Indiana High School Book Award (2008)', 'Lincoln Award (2008)', 'Literaturpreis der Jury der jungen Leser for Cover (2007)', 'Prix Et-lisez-moi (2008)', 'Missouri Gateway Readers Award (2008)']",
      "numRatings": "4964519",
      "ratingsByStars": "['1751460', '1113682', '1008686', '542017', '548674']",
      "likedPercent": "78",
      "setting": "['Forks, Washington (United States)', 'Phoenix, Arizona (United States)', 'Washington (state) (United States)']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1361039443l/41865.jpg",
      "bbeScore": "1459448",
      "bbeVotes": "14874",
      "price": "2.1"
    },
    {
      "bookId": "19063.The_Book_Thief",
      "title": "The Book Thief",
      "series": "",
      "author": "Markus Zusak (Goodreads Author)",
      "rating": "4.37",
      "description": "Librarian's note: An alternate cover edition can be found hereIt is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will be busier still.By her brother's graveside, Liesel's life is changed when she picks up a single object, partially hidden in the snow. It is The Gravedigger's Handbook, left behind there by accident, and it is her first act of book thievery. So begins a love affair with books and words, as Liesel, with the help of her accordian-playing foster father, learns to read. Soon she is stealing books from Nazi book-burnings, the mayor's wife's library, wherever there are books to be found.But these are dangerous times. When Liesel's foster family hides a Jew in their basement, Liesel's world is both opened up, and closed down.In superbly crafted writing that burns with intensity, award-winning author Markus Zusak has given us one of the most enduring stories of our time.(Note: this title was not published as YA fiction)",
      "language": "English",
      "isbn": "9780375831003",
      "genres": "Нехудожественная литература",
      "characters": "['Liesel Meminger', 'Hans Hubermann', 'Rudy Steiner', 'Rosa Hubermann', 'Max Vandenburg', 'Tommy Müller', 'Ilsa Hermann', 'Frau Holtzapfel']",
      "bookFormat": "Hardcover",
      "edition": "First American Edition",
      "pages": "552",
      "publisher": "Alfred A. Knopf",
      "publishDate": "03/14/06",
      "firstPublishDate": "09/01/05",
      "awards": "['National Jewish Book Award for Children’s and Young Adult Literature (2006)', Book Sense Book of the Year Award for Children's Literature (2007), 'Buxtehuder Bulle (2008)', 'Sydney Taylor Book Award for Teen Readers (2007)', 'Prijs van de Kinder- en Jeugdjury Vlaanderen (2009)', 'Michael L. Printz Award Nominee (2007)', 'Exclusive Books Boeke Prize (2007)', 'Rhode Island Teen Book Award Nominee (2008)', 'The Quill Award Nominee for Young Adult/Teen (2006)', 'Zilveren Zoen (2008)', 'Teen Read Award Nominee for Best All-Time-Fave (2010)', 'Deutscher Jugendliteraturpreis for Preis der Jugendjury (2009)', 'Association of Jewish Libraries for Teen Book Award (2006)', 'Lincoln Award Nominee (2010)', 'Australian Book Industry Award (ABIA) Nominee for Literary Fiction (2008)', 'Kathleen Mitchell Award', 'Ena Noel Award (2008)', 'Literaturpreis der Jury der jungen Leser for Jugendbuch (2009)', 'LovelyBooks Leserpreis for Allgemeine Literatur (2009)', 'Margaret A. Edwards Award (2014)']",
      "numRatings": "1834276",
      "ratingsByStars": "['1048230', '524674', '186297', '48864', '26211']",
      "likedPercent": "96",
      "setting": "['Molching (Germany)', 'Germany']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1522157426l/19063._SY475_.jpg",
      "bbeScore": "1372809",
      "bbeVotes": "14168",
      "price": "3.8"
    },
    {
      "bookId": "11127.The_Chronicles_of_Narnia",
      "title": "The Chronicles of Narnia",
      "series": "The Chronicles of Narnia (Publication Order) #1–7",
      "author": "C.S. Lewis, Pauline Baynes (Illustrator)",
      "rating": "4.26",
      "description": "Journeys to the end of the world, fantastic creatures, and epic battles between good and evil—what more could any reader ask for in one book? The book that has it all is The Lion, the Witch and the Wardrobe, written in 1949 by Clive Staples Lewis. But Lewis did not stop there. Six more books followed, and together they became known as The Chronicles of Narnia.For the past fifty years, The Chronicles of Narnia have transcended the fantasy genre to become part of the canon of classic literature. Each of the seven books is a masterpiece, drawing the reader into a land where magic meets reality, and the result is a fictional world whose scope has fascinated generations.This edition presents all seven books—unabridged—in one impressive volume. The books are presented here in chronlogical order, each chapter graced with an illustration by the original artist, Pauline Baynes. Deceptively simple and direct, The Chronicles of Narnia continue to captivate fans with adventures, characters, and truths that speak to readers of all ages, even fifty years after they were first published.",
      "language": "English",
      "isbn": "9999999999999",
      "genres": "Книги для детей",
      "characters": "['Polly', 'Aslan', 'Lucy Pevensie', 'Edmund Pevensie', 'Eustace Scrubb', 'Prince Caspian', 'Jill Pole', 'Prince Rilian', 'Puddleglum', 'Trumpkin', 'Jewel', 'Aravis', 'Mr. Tumnus', 'Puzzle', 'King Tirian', 'Digory Kirke', 'Peter Pevensie', 'Susan Pevensie', 'Reepicheep', 'Jadis', 'Bacchus (god)', 'Mr. & Mrs. Beaver', 'Andrew Kirke', 'Shasta', 'Silenus', 'Nikabrik', 'King Miraz', 'Dr. Cornelius', 'Trufflehunter', 'Shift']",
      "bookFormat": "Paperback",
      "edition": "Reissue Edition",
      "pages": "767",
      "publisher": "HarperCollins",
      "publishDate": "09/16/02",
      "firstPublishDate": "10/28/56",
      "awards": "[]",
      "numRatings": "517740",
      "ratingsByStars": "['254964', '167572', '74362', '15423', '5419']",
      "likedPercent": "96",
      "setting": "['London, England']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1449868701l/11127._SY475_.jpg",
      "bbeScore": "1238556",
      "bbeVotes": "12949",
      "price": ""
    },
    {
      "bookId": "18405.Gone_with_the_Wind",
      "title": "Gone with the Wind",
      "series": "",
      "author": "Margaret Mitchell",
      "rating": "4.30",
      "description": "Scarlett O'Hara, the beautiful, spoiled daughter of a well-to-do Georgia plantation owner, must use every means at her disposal to claw her way out of the poverty she finds herself in after Sherman's March to the Sea.",
      "language": "English",
      "isbn": "9780446675536",
      "genres": "Религия",
      "characters": "[Scarlett O'Hara, 'Rhett Butler', 'Ashley Wilkes', 'Melanie Hamilton Wilkes', 'Wade Hampton Hamilton', 'Ella Lorena Kennedy', 'Eugenie Victoria Bonnie Blue Butler', 'Beau Wilkes', 'India Wilkes', 'Honey Wilkes', 'John  Wilkes', Gerald O'Hara, Ellen O'Hara, Suellen O'Hara, Carreen O'Hara, 'Eulalie', 'Pauline', 'Mammy Abigail', 'Prissy', 'Pork', 'Dilcey', 'Charles Hamilton', 'Frank Kennedy', 'Belle Watling', 'Jonas Wilkerson', 'Emmie Slattery', 'Will Benteen', 'Aunt Pittypat Hamilton', 'Uncle Peter']",
      "bookFormat": "Mass Market Paperback",
      "edition": "",
      "pages": "1037",
      "publisher": "Warner Books",
      "publishDate": "04/01/99",
      "firstPublishDate": "06/30/36",
      "awards": "['Pulitzer Prize for Novel (1937)', 'National Book Award for Novel (1936)']",
      "numRatings": "1074620",
      "ratingsByStars": "['602138', '275517', '133535', '39008', '24422']",
      "likedPercent": "94",
      "setting": "['Atlanta, Georgia (United States)']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1551144577l/18405._SY475_.jpg",
      "bbeScore": "1087732",
      "bbeVotes": "11211",
      "price": "5.58"
    },
    {
      "bookId": "11870085-the-fault-in-our-stars",
      "title": "The Fault in Our Stars",
      "series": "",
      "author": "John Green (Goodreads Author)",
      "rating": "4.21",
      "description": "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten.Insightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning author John Green's most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love.",
      "language": "English",
      "isbn": "9999999999999",
      "genres": "Комиксы",
      "characters": "['Hazel Grace Lancaster', 'Augustus Waters', 'Isaac']",
      "bookFormat": "Hardcover",
      "edition": "",
      "pages": "313",
      "publisher": "Dutton Books",
      "publishDate": "01/10/12",
      "firstPublishDate": "",
      "awards": "['Georgia Peach Book Award (2013)', 'Buxtehuder Bulle (2012)', 'Odyssey Award (2013)', 'Audie Award for Teens (2013)', West Australian Young Readers' Book Award (WAYRBA) for Older Readers (2013), Pennsylvania Young Readers' Choice Award for Young Adults (2013), 'Rhode Island Teen Book Award (2014)', 'Evergreen Teen Book Award (2015)', 'Soaring Eagle Book Award (2014)', 'Milwaukee County Teen Book Award (2013)', 'Indies Choice Book Award for Young Adult (2013)', 'Deutscher Jugendliteraturpreis for Preis der Jugendjury (2013)', 'Amelia Elizabeth Walden Award (2013)', 'Dioraphte Jongerenliteratuurprijs for vertaald boek en publieksprijs (2013)', 'The Inky Awards for Silver Inky (2012)', 'California Young Readers Medal for Young Adult (2015)', 'Lincoln Award (2014)', 'Luisterboek Award (2015)', 'Goodreads Choice Award for Young Adult Fiction (2012) and Nominee for Best of the Best  (2018)', 'Green Mountain Book Award (2014)', 'The Inky Awards Shortlist for Silver Inky (2012)', Louisiana Teen Readers' Choice (2015), 'Missouri Gateway Readers Award (2015)', 'Oklahoma Sequoyah Award for High School (2015)', 'Alabama Author Award for Young Adult (2013)', 'Premio El Templo de las Mil Puertas for Mejor novela extranjera independiente (2012)', 'FAB Award Nominee (2014)', 'Premi Protagonista Jove for Categoria 15-16 anys (2013)']",
      "numRatings": "3550714",
      "ratingsByStars": "['1784471', '1022406', '512574', '150365', '80898']",
      "likedPercent": "93",
      "setting": "['Indianapolis, Indiana (United States)', 'Amsterdam (Netherlands)']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1360206420l/11870085.jpg",
      "bbeScore": "1087056",
      "bbeVotes": "11287",
      "price": ""
    },
    {
      "bookId": "386162.The_Hitchhiker_s_Guide_to_the_Galaxy",
      "title": "The Hitchhiker's Guide to the Galaxy",
      "series": "The Hitchhiker's Guide to the Galaxy #1",
      "author": "Douglas Adams",
      "rating": "4.22",
      "description": "Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide (A towel is about the most massively useful thing an interstellar hitchhiker can have) and a galaxy-full of fellow travelers: Zaphod Beeblebrox—the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy",
      "language": " Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone",
      "isbn": " Marvin, a paranoid, brilliant, and chronically depressed robot",
      "genres": "Комиксы",
      "characters": "English",
      "bookFormat": "9999999999999",
      "edition": "['Science Fiction', 'Fiction', 'Humor', 'Fantasy', 'Classics', 'Comedy', 'Science Fiction Fantasy', 'Audiobook', 'Adventure', 'Novels']",
      "pages": "['Zaphod Beeblebrox', 'Arthur Dent', 'Ford Prefect', 'Trillian', 'Marvin, the paranoid android', 'Slartibartifast']",
      "publisher": "Paperback",
      "publishDate": "",
      "firstPublishDate": "193",
      "awards": "Del Rey",
      "numRatings": "06/23/07",
      "ratingsByStars": "10/12/79",
      "likedPercent": "[]",
      "setting": "1436325",
      "coverImg": "['725771', '420864', '199846', '58326', '31518']",
      "bbeScore": "94",
      "bbeVotes": "[]",
      "price": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1559986152l/386162.jpg"
    },
    {
      "bookId": "370493.The_Giving_Tree",
      "title": "The Giving Tree",
      "series": "",
      "author": "Shel Silverstein",
      "rating": "4.37",
      "description": "Once there was a tree...and she loved a little boy.So begins a story of unforgettable perception, beautifully written and illustrated by the gifted and versatile Shel Silverstein.Every day the boy would come to the tree to eat her apples, swing from her branches, or slide down her trunk...and the tree was happy. But as the boy grew older he began to want more from the tree, and the tree gave and gave and gave.This is a tender story, touched with sadness, aglow with consolation. Shel Silverstein has created a moving parable for readers of all ages that offers an affecting interpretation of the gift of giving and a serene acceptance of another's capacity to love in return.",
      "language": "English",
      "isbn": "9780060256654",
      "genres": "Переодические издания",
      "characters": "[]",
      "bookFormat": "Hardcover",
      "edition": "",
      "pages": "64",
      "publisher": "HarperCollins Publishers",
      "publishDate": "10/07/64",
      "firstPublishDate": "10/28/64",
      "awards": "[]",
      "numRatings": "905731",
      "ratingsByStars": "['556142', '204347', '94819', '27950', '22473']",
      "likedPercent": "94",
      "setting": "[]",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1174210942l/370493._SX318_.jpg",
      "bbeScore": "1021534",
      "bbeVotes": "10594",
      "price": "4.87"
    },
    {
      "bookId": "968.The_Da_Vinci_Code",
      "title": "The Da Vinci Code",
      "series": "Robert Langdon #2",
      "author": "Dan Brown (Goodreads Author)",
      "rating": "3.86",
      "description": "ISBN 9780307277671 moved to this edition.While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.",
      "language": "English",
      "isbn": "9999999999999",
      "genres": "Учебная литература",
      "characters": "['Sophie Neveu', 'Robert Langdon', 'Sir Leigh Teabing', 'Silas (The Da Vinci Code)', 'Bezu Fache', 'Jerome Collet', 'Manuel Aringarosa', 'Rémy Legaludec', 'André Vernet']",
      "bookFormat": "Paperback",
      "edition": "",
      "pages": "489",
      "publisher": "Anchor",
      "publishDate": "03/28/06",
      "firstPublishDate": "03/18/03",
      "awards": "['British Book Award for Book of the Year (2005)', 'Book Sense Book of the Year Award for Adult Fiction (2004)', Humo's Gouden Bladwijzer (2004), 'Zilveren Vingerafdruk (2004)', The Flume: New Hampshire Teen Reader's Choice Award (2006), 'Teen Buckeye Book Award (2005)', 'Iowa High School Book Award (2006)', 'Puddly Award for Fiction (2007)', 'Missouri Gateway Readers Award for Adult (2006)']",
      "numRatings": "1933446",
      "ratingsByStars": "['645308', '667657', '399278', '142103', '79100']",
      "likedPercent": "89",
      "setting": "['Paris (France)', 'London, England', 'France', 'England', 'United Kingdom']",
      "coverImg": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1579621267l/968.jpg",
      "bbeScore": "876633",
      "bbeVotes": "9231",
      "price": ""
    },
]